export const USER_LOGIN = 'USER_LOGIN';
export const GET_WALLET_CURRENCIES = 'GET_WALLET_CURRENCIES';
export const GET_WALLET_EXPENSES = 'GET_WALLET_EXPENSES';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
